const songs = [
  {
    id: 0,
    title: "Lost in the City Lights",
    artist: "Cosmo Sheldrake",
    duration: "1:12",
    cover: "../assets/images/cover-1.png",
    src: "../assets/mp3/lost-in-city-lights.mp3",
    genre: "lofi",
  },
  {
    id: 1,
    title: "Forest Lullaby",
    artist: "Lesfm",
    duration: "2:18",
    cover: "../assets/images/cover-2.png",
    src: "../assets/mp3/forest-lullaby.mp3",
    genre: "lofi",
  },
  {
    id: 2,
    title: "Abran Paso",
    artist: "Larry Harlow",
    duration: "3:32",
    cover: "../assets/images/abran-paso-cover.png",
    src: "../assets/mp3/abran-paso.mp3",
    genre: "salsa",
  },
  {
    id: 3,
    title: "Cara De Payaso",
    artist: "Ismael Rivera",
    duration: "2:35",
    cover: "../assets/images/ismael-rivera-cover.png",
    src: "../assets/mp3/cara-de-payaso.mp3",
    genre: "salsa",
  },
  {
    id: 4,
    title: "Dueña De Mi Inspiracion",
    artist: "Ismael Rivera",
    duration: "3:24",
    cover: "../assets/images/ismael-rivera-cover.png",
    src: "../assets/mp3/duenia-de-mi-inspiracion.mp3",
    genre: "salsa",
  },
  {
    id: 5,
    title: "El Incomprendido",
    artist: "Ismael Rivera",
    duration: "2:56",
    cover: "../assets/images/ismael-rivera-cover.png",
    src: "../assets/mp3/el-incomprendido.mp3",
    genre: "salsa",
  },
  {
    id: 6,
    title: "Yambeque",
    artist: "Sonora Ponceña",
    duration: "6:24",
    cover: "../assets/images/yambeque-cover.png",
    src: "../assets/mp3/yambeque.mp3",
    genre: "salsa",
  },
  {
    id: 7,
    title: "Con Mi Corazon Te Espero",
    artist: "Roberto Ledesma",
    duration: "3:04",
    cover: "../assets/images/te-espero-cover.png",
    src: "../assets/mp3/con-mi-corazon-te-espero.mp3",
    genre: "bolero",
  },
  {
    id: 8,
    title: "Corazon Sin Puerto",
    artist: "Nelson Pinedo",
    duration: "2:54",
    cover: "../assets/images/corazon-sin-puerto-cover.png",
    src: "../assets/mp3/corazon-sin-puerto.mp3",
    genre: "bolero",
  },
  {
    id: 9,
    title: "Hola Soledad",
    artist: "Rolando Laserie",
    duration: "2:49",
    cover: "../assets/images/hola-soledad-cover.png",
    src: "../assets/mp3/hola-soledad.mp3",
    genre: "bolero",
  },
  {
    id: 10,
    title: "Todo Me Gusta De Ti",
    artist: "Alberto Beltran",
    duration: "2:37",
    cover: "../assets/images/todo-me-gusta-de-ti-cover.png",
    src: "../assets/mp3/todo-me-gusta-de-ti.mp3",
    genre: "bolero",
  },
  {
    id: 11,
    title: "Vete De Mi",
    artist: "Altemar Dutra",
    duration: "2:24",
    cover: "../assets/images/vete-de-mi-cover.png",
    src: "../assets/mp3/vete-de-mi.mp3",
    genre: "bolero",
  },
];

export default songs;
